### ISSUE TITLE
Riru 19 （Q beta3）无法使用

### ISSUE THREAD

**Issue by Mystery00** [eritpchy/Fingerprint-pay-magisk-alipay#1]
Android版本：Android Q beta 3
Riru版本 19
插件版本 3.9.2/3

Riru 模块需要更新，参见riru仓库，Android Q beta3无法使用旧版Riru

**Comment by eritpchy** [comment]
指纹插件没有要求使用旧版的 Riru

**Comment by eritpchy** [comment]
fixed
