### ISSUE TITLE
madisk20.4安装失败

### ISSUE THREAD

**Issue by LRYsboyfriend** [eritpchy/Fingerprint-pay-magisk-alipay#10]
![Screenshot_20200423-045506](https://user-images.githubusercontent.com/56359749/80033372-2cc7e680-851f-11ea-94d6-84b79aabe0b4.png)
安装之后不显示信息，支付宝里也没有指纹选项

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/ea010c2fa0e4445e81a811747089bd80ec86ec14
