### ISSUE TITLE
扫码支付出现问题

### ISSUE THREAD

**Issue by Asstiff** [eritpchy/Fingerprint-pay-magisk-alipay#11]
扫码支付会出现 “Oops… 输入失败了. 请手动输入密码 ”的错误。请问可以修复一下吗？感激不尽！

**Comment by eritpchy** [comment]
上传下日志

**Comment by Asstiff** [comment]
> 上传下日志

您好，
感谢您的回复！但是我现在似乎无法复现，我将在下次复现时回复您。
非常感谢！

**Comment by eritpchy** [comment]
复现时打开这个issue
