### ISSUE TITLE
支付宝一个周不可以用

### ISSUE THREAD

**Issue by rp4k** [eritpchy/Fingerprint-pay-magisk-alipay#14]
![20200825_131826](https://user-images.githubusercontent.com/18055235/91126262-2cf70f00-e6d6-11ea-8c7a-a7c1aecd000e.jpg)
一个周不可以用在支付宝。

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/a3cdd6198381fdd02b55601f59f012bb7ebabb51
