### ISSUE TITLE
最新版支付宝失效

### ISSUE THREAD

**Issue by gthanmon** [eritpchy/Fingerprint-pay-magisk-alipay#15]
最新版支付宝插件用不了了 好像别人的xp收能量的模块也用不了了

**Comment by eritpchy** [comment]
空了会更新的

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/a3cdd6198381fdd02b55601f59f012bb7ebabb51
