### ISSUE TITLE
Oops.. 输入失败了. 请手动输入密码

### ISSUE THREAD

**Issue by codyray2015** [eritpchy/Fingerprint-pay-magisk-alipay#16]
嘿，我的设备是Pixel4XL 我尝试使用Fingerprint时通过验证后密码输入貌似失败了，我是通过Fingerprint 配合 FingerFace 使用人脸识别，以下是一些环境信息

Android Ver : R
AliPay Ver : 10.2.0 - Google Play
Fingerprint Ver : 3.9.12
FingerFace  Ver : 1.1.0
Magisk Ver : Canary 20426
Magisk Manager : Canary 300

**Comment by seardna** [comment]
同样问题，我的是只用了Fingerprint
10.2.0.9000
Magisk Ver : Canary 20426
Magisk Manager : Canary 300

**Comment by JhihYuWong** [comment]
+1

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/cdea520296f1e48797ebbd248106efed1b2e653f
