### ISSUE TITLE
模块更新到3.9.20后支付时提示失败

### ISSUE THREAD

**Issue by maidmeow4** [eritpchy/Fingerprint-pay-magisk-alipay#17]
Magisk 20.4
支付宝 10.2.0.8026 (Google Play)

支付时提示指纹识别成功，随后又提示失败请手动输入支付密码。
尝试了在Magisk Manager中 ❌ 取消勾选 再 ✔️ 勾选 模块并重启手机，问题未解决。

**Comment by chaofanlin** [comment]
一样的问题，play版10.2.0.8026，更新了magisk8.0

**Comment by eritpchy** [comment]
请升级至最新版本

**Comment by chaofanlin** [comment]
> 请升级至最新版本

就是最新的模块3.9.20

**Comment by eritpchy** [comment]
请更新支付宝至最新版

**Comment by maidmeow4** [comment]
> 
> 请更新支付宝至最新版

Google Play 商店目前无更新版本，无法更新。 ([Google Play商店页面](https://play.google.com/store/apps/details?id=com.eg.android.AlipayGphone&hl=zh))

**Comment by eritpchy** [comment]
https://www.weidown.com/android/soft/474.html

**Comment by maidmeow4** [comment]
https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/releases/tag/3.9.20

> 适配支付宝10.2.0.8026 版本(Play)

**Comment by eritpchy** [comment]
改好了 谢谢提醒

**Comment by maidmeow4** [comment]
我无话可说了。
@chaofanlin
