### ISSUE TITLE
pixel 4 xl 无法正常使用

### ISSUE THREAD

**Issue by ffllc** [eritpchy/Fingerprint-pay-magisk-alipay#18]
你好  我是用pixel 4 xl手机。  安装太极把指纹识别转换成面部识别。  微信模块工作正常，但是支付宝模块， 在输入密码时能够跳出面部识别请求，但是面部识别成功后会提示输入密码失败，  然后还是要手工输入。请问如何解决  谢谢

**Comment by eritpchy** [comment]
提供支付宝，指纹支付版本截图

**Comment by oldcatzhang** [comment]
> 提供支付宝，指纹支付版本截图

我跟这位一样的情况，用的您的Xposed-Fingerprint-pay，这里文本回复了先，支付宝就是10.2.0.8026，play商店下载的；指纹支付是最新的3.9.20。

**Comment by eritpchy** [comment]
请升级至最新版本 10.2.3.8443





https://www.weidown.com/android/soft/474.html

**Comment by oldcatzhang** [comment]
> 请升级至最新版本 10.2.3.8443 https://www.weidown.com/android/soft/474.html

升级到这个版本也不行，表现是一样的

**Comment by eritpchy** [comment]
哦

**Comment by notorangee** [comment]
一样，同pixel 4 xl

**Comment by eritpchy** [comment]
过于久远,先行关闭
