### ISSUE TITLE
关于libs的疑问

### ISSUE THREAD

**Issue by wukuai** [eritpchy/Fingerprint-pay-magisk-alipay#21]
请问下libs文件夹下的apk文件是怎么生成的呢：

即：module/libs/fingerprint-pay-alipay-magisk.apk

**Comment by eritpchy** [comment]
参考Xposed指纹支付编译出来

**Comment by wukuai** [comment]
我目前使用该项目libs下的apk文件可以成功编译并在手机上正常运行，
使用xposed指纹支付项目编译(包括debug和release)出来的apk文件作为libs下的apk文件，能编译安装，但打开支付宝就黑屏，下载xposed指纹支付项目发布的apk文件作为libs再编译也是同样打开支付宝黑屏。
我想做一些定制开发，请问下有一些开发者指南的编译发布说明吗？

**Comment by eritpchy** [comment]
没有，不能二次开发

**Comment by wukuai** [comment]
请问下 module/libs/fingerprint-pay-alipay-magisk.apk 最新版的源码有开源吗 ？

**Comment by eritpchy** [comment]
没有
