### ISSUE TITLE
3.9.20版本，在其他APP调用支付宝付款的情况下无法正常使用

### ISSUE THREAD

**Issue by noka233** [eritpchy/Fingerprint-pay-magisk-alipay#23]
如题，只要不是在支付宝内创建的付款，指纹支付就无法正常生效，提示识别失败然后输入密码
Android 10，Magisk 20.4

**Comment by noka233** [comment]
忘记说了，基于riru 21.3版本，因为更高的版本无法使用Alpha版本的EdXposed

**Comment by eritpchy** [comment]
更新到最新版试试?

**Comment by N2022062** [comment]
你的ALI没冻结么？
