### ISSUE TITLE
Magiskhide下把alipay的选项会影响支付么？

### ISSUE THREAD

**Issue by N2022062** [eritpchy/Fingerprint-pay-magisk-alipay#24]
我这toast显示指纹识别成功 但是还要输入密码 好几次了

如果不是那可能是android11的问题了

**Comment by N2022062** [comment]
今天试了还是提示手动输入密码
不知道是android11的问题还是新riru的问题

**Comment by eritpchy** [comment]
不确定, 请尝试更新到最新版本

**Comment by N2022062** [comment]
试了 机型就不支持 除非用衍生魔改系统 已经曲线解决，多谢回复！
