### ISSUE TITLE
安装不了模块

### ISSUE THREAD

**Issue by lybf** [eritpchy/Fingerprint-pay-magisk-alipay#26]
![Screenshot_20210120-100711](https://user-images.githubusercontent.com/23008147/105117398-5f7f2980-5b07-11eb-8d30-66014ef82e5a.jpg)
![Screenshot_20210120-100818](https://user-images.githubusercontent.com/23008147/105117435-6dcd4580-5b07-11eb-866c-fd7d321a35c4.jpg)
安装不了模块，这是啥原因呢，不太懂

**Comment by N2022062** [comment]
不支持 riru23

**Comment by eritpchy** [comment]
看起来已经装上了

**Comment by lybf** [comment]
> 看起来已经装上了

已经能用了，不过xposed插件版的貌似用不了（vx8.0 qq也是）
