### ISSUE TITLE
更新支付宝10.2.12后模块失效

### ISSUE THREAD

**Issue by chaofanlin** [eritpchy/Fingerprint-pay-magisk-alipay#27]
今天更新了play的支付宝，版本号10.2.12后指纹模块用不了了。
3.9.21模块，在设置里面可以看得到，但是支付时就是只能手动输入密码

**Comment by musva** [comment]
我也用不了
支付宝 play版 v10.2.12
Riru v23.4
模块 v3.9.21

感谢

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/releases/tag/3.9.22

**Comment by heyxiaobai** [comment]
一样的问题，更新后依旧存在

支付宝 play版 v10.2.12
Riru v23.4
模块 v3.9.22

希望可以快点修复啦
