### ISSUE TITLE
3.9.22 版本指纹界面异常黑色

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [eritpchy/Fingerprint-pay-magisk-alipay#28]
![Screenshot_20210206-131625_Alipay](https://user-images.githubusercontent.com/63704404/107109752-c7f73600-687d-11eb-8644-119e2fc08a4c.png)
如题。并没有开启强制夜间模式。

**Comment by fang5566** [comment]
我也是

**Comment by eritpchy** [comment]
fixed,  https://github.com/eritpchy/FingerprintPay/releases/tag/4.0.0
