### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by mclovin-2k** [eritpchy/Fingerprint-pay-magisk-alipay#30]
设备：OnePlus 8 Pro
系统：Oxygen OS 11.0.5.5.IN11AA
支付宝版本：10.2.23.5839 (GooglePlay)
Magisk：23.0
Riru：
![image](https://user-images.githubusercontent.com/5440567/122535458-29ae8480-d056-11eb-8333-b90ef0c27404.png)

只要安装了本模块，重启之后，打开支付宝必闪退。
日志：（90行开始）
[logcat.txt](https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/files/6675930/logcat.txt)

卸载本模块，重启之后，支付宝正常。

**Comment by eritpchy** [comment]
只开启留指纹插件和Riru试试

**Comment by mclovin-2k** [comment]
经过反复试验。
最终发现问题是由Magisk Hide引起的。
只要对支付宝打开Hide，再加上本模块，就会引起闪退。
从日志看似乎是无法访问"/system/framework/"路径下的文件？
可能需要适配一下？

**Comment by fang5566** [comment]
和楼上相同，必须解除对支付宝的hide才可以。部分类原生ROM不支持支付宝指纹支付，必须刷这个模块，但是hide又影响模块作用。希望老大适配一下。
