### ISSUE TITLE
无法在riru 26版本使用

### ISSUE THREAD

**Issue by lanruqing** [eritpchy/Fingerprint-pay-magisk-alipay#32]
![Screenshot_20210808-085959](https://user-images.githubusercontent.com/13705679/128617431-c45e2a19-b435-46e5-85eb-6e8d7a01a16f.png)

![Screenshot_20210808-090013](https://user-images.githubusercontent.com/13705679/128617442-18c67fc6-29c3-4bf9-bfcd-659c7d0774cc.png)

**Comment by eritpchy** [comment]
待安排

**Comment by eritpchy** [comment]
fixed,  https://github.com/eritpchy/FingerprintPay/releases/tag/4.0.0
