### ISSUE TITLE
在Magisk v20.2 上无法正常工作

### ISSUE THREAD

**Issue by pssyz** [eritpchy/Fingerprint-pay-magisk-alipay#4]
在Magisk v20.2 上无法正常工作 ，支付宝设置中不显示指纹设置选项
使用的都是riru core 19.5 版本，和最新的Fingerprint-pay-magisk-alipay模块，支付宝10.1.82，乐视 乐Max 2  ，Android 10 , 这些都是完全相同的情况下，一旦退回到Magisk v20.1，一切都恢复正常！
Fingerprint-pay-magisk-wechat也是这个情况！

**Comment by eritpchy** [comment]
感谢反馈

**Comment by sancholive** [comment]
我也是同样的问题，在Magisk v20.2 上无法正常工作 ，支付宝和微信设置中都不显示指纹设置选项
使用的都是riru core 19.5 版本，和最新的支付宝和微信magisk指纹支付模块 机型Pixel 3 xl ，Android 10

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/adfdacfb0cc17c053c832828185de288e1a10892
