### ISSUE TITLE
能否在指纹确认时加个震动提示

### ISSUE THREAD

**Issue by N2022062** [eritpchy/Fingerprint-pay-magisk-alipay#5]
类似ios那种？

**Comment by eritpchy** [comment]
👍

**Comment by N2022062** [comment]
希望考虑下

**Comment by XianyuCen** [comment]
双重震动了！大佬，可以来个没有震动的嘛，非常感谢

**Comment by eritpchy** [comment]
振动并非来自于插件

**Comment by XianyuCen** [comment]
以前的版本只有一个震动，这个版本是两个，我也不太懂

**Comment by eritpchy** [comment]
刚刚核对过, 震动并非来自于插件

**Comment by XianyuCen** [comment]
好的

**Comment by XianyuCen** [comment]
感谢大佬

**Comment by N2022062** [comment]
这个插件目前没震动，你的双震和这个无关。。。。

**Comment by XianyuCen** [comment]
大佬，您好，最新版指纹支付宝无效了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eritpchy/Fingerprint-pay-magisk-alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 下午4:40
收件人:&nbsp;"eritpchy/Fingerprint-pay-magisk-alipay"<Fingerprint-pay-magisk-alipay@noreply.github.com&gt;;
抄送:&nbsp;"咸鱼Cen"<1796653549@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eritpchy/Fingerprint-pay-magisk-alipay] 能否在指纹确认时加个震动提示 (#5)





 
刚刚核对过, 震动并非来自于插件
