### ISSUE TITLE
支付宝支付窗口变更

### ISSUE THREAD

**Issue by Asstiff** [eritpchy/Fingerprint-pay-magisk-alipay#6]
开发者您好！

### 我注意到支付宝的支付窗口在最近发生了变化

![Screenshot_20200226-161001](https://user-images.githubusercontent.com/46558763/75347631-1ebd6700-58dc-11ea-8c00-7c77896ce26e.png)
**上图为旧版**

![-62e4d8e6781b4d3](https://user-images.githubusercontent.com/46558763/75348141-334e2f00-58dd-11ea-93b8-ebab38affa19.jpg)
**上图为新版**

### 变更之后，指纹支付模块就不管用了

![-31172abd74df1ce5](https://user-images.githubusercontent.com/46558763/75348287-7e684200-58dd-11ea-85b9-58bb36a92232.jpg)
**变更之后，指纹支付模块出错**

请问能不能修复一下呢？
我十分喜欢您的工作，同时也非常感谢您！
祝您好运！

**Comment by pinoyo** [comment]
我也碰到了，安装后从来没使用过，今天第一次使用，提示：oops..输入失败了，然后还是输入密码

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/65fb440dc315951b22fbc9cd56614e64d9f6869f
