### ISSUE TITLE
开启后仍出现输入密码界面

### ISSUE THREAD

**Issue by Sun-V** [eritpchy/Fingerprint-pay-magisk-alipay#7]
开发者你好，感谢你的工作。我使用的模块和支付宝（play版）都是最新版，但仍存在已关闭的“支付宝支付窗口变更”问题。

**Comment by eritpchy** [comment]
录像看看， 版本号也要录进去

**Comment by Sun-V** [comment]
> 录像看看， 版本号也要录进去

触摸到指纹后在录屏中黑屏，实际操作无黑屏现象。
https://drive.google.com/file/d/1-jwyZ00IL27CldfQFko3qE7j0f_lig70/view?usp=drivesdk

**Comment by eritpchy** [comment]
你是最新版???
<img width="370" alt="QQ20200304-233701@2x" src="https://user-images.githubusercontent.com/8630635/75895805-1d0e1900-5e71-11ea-9eea-139b6165f8e3.png">

**Comment by eritpchy** [comment]
能用另一台手机录像吗

**Comment by eritpchy** [comment]
经测试play版确实有这个问题, 国内版没问题

**Comment by xxyzuo** [comment]
> 经测试play版确实有这个问题, 国内版没问题
play同有这个问题，可以修复吗

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/573ab68af9ad2f8880ed9d6e208616d51f8cdee0
