### ISSUE TITLE
pe plus 插件不认

### ISSUE THREAD

**Issue by N2022062** [eritpchy/Fingerprint-pay-magisk-alipay#8]
PLAY最新版alipay
magisk下插件标题下显示三行（未提供信息）
应该是PE PLUS系统问题
XP插件可以用，但还是喜欢这个
不知道可以修复么？

**Comment by eritpchy** [comment]
https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/issues/19#issuecomment-608980532
测试类似的问题并反馈

**Comment by N2022062** [comment]
![Screenshot_20200414-221520273](https://user-images.githubusercontent.com/6193203/79235333-0c07ed00-7e9e-11ea-8aae-4484a6d8f2a2.jpg)




![Screenshot_20200414-221323711](https://user-images.githubusercontent.com/6193203/79234993-9e5bc100-7e9d-11ea-92f5-a199be4fdf8c.jpg)


![Screenshot_20200414-221520273](https://user-images.githubusercontent.com/6193203/79235333-0c07ed00-7e9e-11ea-8aae-4484a6d8f2a2.jpg)
[](url)
![Screenshot_20200414-221506904](https://user-images.githubusercontent.com/6193203/79235724-90f30680-7e9e-11ea-9131-ccceb7548d33.jpg)

**Comment by N2022062** [comment]
![Screenshot_20200414-222424754](https://user-images.githubusercontent.com/6193203/79235876-c1d33b80-7e9e-11ea-8b30-5f28f0cbe58b.jpg)

**Comment by eritpchy** [comment]
我是问你链接最后的文件能用不

**Comment by N2022062** [comment]
WECHAT的可以

**Comment by eritpchy** [comment]
ok等待更新

**Comment by N2022062** [comment]
多谢朋友！

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-alipay/commit/ea010c2fa0e4445e81a811747089bd80ec86ec14
